[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "hope sauce raccoon kitten dirt hard cram gown promote pyramid absent tackle process bring swift robust disorder discover spend business require aware split rely"
